apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xcm7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xcm7
    app.kubernetes.io/part-of: ci1t-830-0043-app
  name: devfile-sample-xcm7
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xcm7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xcm7
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0043-tenant/ci1t-830-0043-app/devfile-sample-xcm7@sha256:2df8323cad9c937c10ea273e005465c96b9f4ae3d47bc0b84fd303290c232330
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
